<?php

namespace OneToMany\LlmSdk\Contract\Response\Query;

use OneToMany\LlmSdk\Contract\Response\Usage\TokenUsageInterface;

interface QueryResponseInterface
{
    /**
     * The complete LLM API response body.
     *
     * @return array<int|string, mixed>
     */
    public function __invoke(): array;

    /**
     * Unique identifier provided by the LLM API.
     *
     * @return ?non-empty-string
     */
    public function getUri(): ?string;

    /**
     * Raw output generated by the LLM.
     *
     * @return ?non-empty-string
     */
    public function getOutput(): ?string;

    /**
     * Error message generated by the LLM.
     *
     * @return ?non-empty-string
     */
    public function getError(): ?string;

    /**
     * Total query runtime in milliseconds.
     *
     * @return non-negative-int
     */
    public function getRuntime(): int;

    /**
     * Input, cached, and output tokens used by the query.
     */
    public function getUsage(): TokenUsageInterface;
}
